name: phgy_analysis
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.9
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=10.0.1
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nspr=4.33
  - nss=3.74
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.2.4
  - pcre=8.45
  - pillow=9.3.0
  - pip=22.3.1
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.8.8
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.7
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - scipy=1.6.2
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - charset-normalizer==2.1.1
    - dill==0.3.6
    - emd-signal==1.4.0
    - entropyhub==0.2
    - idna==3.4
    - multiprocess==0.70.14
    - pathos==0.3.0
    - pox==0.3.2
    - ppft==1.7.6.6
    - requests==2.28.1
    - tqdm==4.64.1
    - urllib3==1.26.13
